@echo off
REM ============================================================================
REM HELEN OS - Windows Local Installer
REM Windows equivalent of INSTALL_LOCAL.sh
REM Target: HELEN compute node on Windows + Ollama backend
REM ============================================================================

setlocal enabledelayedexpansion

echo.
echo ================================================================
echo            HELEN OS - LOCAL INSTALLATION (Windows)
echo            Multi-Model Unified AI Companion Setup
echo ================================================================
echo.

REM ---- Check Python ----
echo [1/7] Checking Python...
where python >nul 2>nul
if errorlevel 1 (
    echo   ERROR: python not found on PATH.
    echo   Install Python 3.9+ from https://www.python.org/downloads/windows/
    echo   IMPORTANT: tick "Add Python to PATH" during install.
    goto :fail
)
python --version
python -c "import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)"
if errorlevel 1 (
    echo   ERROR: Python 3.9+ required.
    goto :fail
)
echo   OK
echo.

REM ---- Check Git ----
echo [2/7] Checking Git...
where git >nul 2>nul
if errorlevel 1 (
    echo   ERROR: git not found on PATH.
    echo   Install Git for Windows from https://git-scm.com/download/win
    goto :fail
)
git --version
echo   OK
echo.

REM ---- Check Ollama ----
echo [3/7] Checking Ollama...
where ollama >nul 2>nul
if errorlevel 1 (
    echo   WARNING: ollama not found on PATH.
    echo   Install from https://ollama.com/download/windows
    echo   Continuing anyway - you can install Ollama later.
) else (
    ollama --version
    echo   OK
)
echo.

REM ---- Create venv ----
echo [4/7] Creating virtual environment .venv ...
if exist .venv (
    echo   .venv already exists, skipping creation.
) else (
    python -m venv .venv
    if errorlevel 1 (
        echo   ERROR: failed to create venv.
        goto :fail
    )
    echo   OK
)
echo.

REM ---- Activate + install ----
echo [5/7] Installing Python dependencies...
call .venv\Scripts\activate.bat
if errorlevel 1 (
    echo   ERROR: failed to activate venv.
    goto :fail
)
python -m pip install --upgrade pip setuptools wheel
python -m pip install -r requirements.txt
if errorlevel 1 (
    echo   ERROR: pip install failed. See messages above.
    goto :fail
)
echo   OK
echo.

REM ---- Config dir + .env ----
echo [6/7] Setting up configuration directory...
set "HELEN_CFG=%USERPROFILE%\.helen_os"
if not exist "%HELEN_CFG%" mkdir "%HELEN_CFG%"
set "ENV_FILE=%HELEN_CFG%\.env"
if not exist "%ENV_FILE%" (
    >  "%ENV_FILE%" echo # HELEN OS - API Keys ^& Runtime Config
    >> "%ENV_FILE%" echo # Generated by INSTALL_LOCAL.bat
    >> "%ENV_FILE%" echo.
    >> "%ENV_FILE%" echo # Cloud providers (optional - leave blank for Ollama-only)
    >> "%ENV_FILE%" echo ANTHROPIC_API_KEY=
    >> "%ENV_FILE%" echo OPENAI_API_KEY=
    >> "%ENV_FILE%" echo XAI_API_KEY=
    >> "%ENV_FILE%" echo GOOGLE_API_KEY=
    >> "%ENV_FILE%" echo QWEN_API_KEY=
    >> "%ENV_FILE%" echo.
    >> "%ENV_FILE%" echo # Deployment
    >> "%ENV_FILE%" echo HELEN_ENVIRONMENT=local
    >> "%ENV_FILE%" echo HELEN_DEBUG=false
    >> "%ENV_FILE%" echo HELEN_PORT=8000
    >> "%ENV_FILE%" echo.
    >> "%ENV_FILE%" echo # Runtime - prefer local Ollama on this node
    >> "%ENV_FILE%" echo HELEN_DEFAULT_MODEL=gemma3:12b
    >> "%ENV_FILE%" echo HELEN_TEMPERATURE=0.7
    >> "%ENV_FILE%" echo HELEN_MAX_TOKENS=2048
    >> "%ENV_FILE%" echo HELEN_STREAMING=true
    >> "%ENV_FILE%" echo HELEN_AUTO_FALLBACK=true
    >> "%ENV_FILE%" echo HELEN_PREFER_LOCAL=true
    echo   Created %ENV_FILE%
) else (
    echo   %ENV_FILE% already exists, leaving as-is.
)
echo.

REM ---- Probe Ollama ----
echo [7/7] Probing Ollama at http://localhost:11434 ...
python -c "import urllib.request,sys;\
 r=urllib.request.urlopen('http://localhost:11434/api/tags',timeout=2);\
 print('  OK -', r.status)" 2>nul
if errorlevel 1 (
    echo   Ollama is not responding on localhost:11434.
    echo   Open the Ollama app from the Start menu, or run: ollama serve
    echo   Then verify with: ollama list
) else (
    echo   Ollama reachable.
)
echo.

echo ================================================================
echo   INSTALL COMPLETE
echo ================================================================
echo.
echo Next steps:
echo   1. Make sure Ollama is running (Start menu - Ollama, or: ollama serve)
echo   2. Make sure gemma3:12b is pulled:  ollama list
echo      (if missing:  ollama pull gemma3:12b)
echo   3. Activate the venv in this shell:
echo        .venv\Scripts\activate
echo   4. Boot HELEN:
echo        python helen_unified_interface_v1.py
echo.
echo Config file: %ENV_FILE%
echo.
goto :eof

:fail
echo.
echo Installation aborted.
exit /b 1
