#!/usr/bin/env bash
# ============================================================================
# SETUP_HELEN_NODE.sh — One-shot HELEN compute-node bootstrap for WSL2 Ubuntu
# ============================================================================
# Assumes:
#   - Running inside WSL2 Ubuntu
#   - Ollama on Windows host bound to 0.0.0.0:11434 (run SETUP_OLLAMA_WIN.bat)
# Does:
#   1. Tests the bridge to Windows Ollama (with fallback to host IP)
#   2. apt-installs git/python3/venv/pip/curl
#   3. Clones/updates the helen-conquest repo
#   4. Creates .venv and installs requirements
#   5. Writes ~/.helen_os/.env pointing at Windows Ollama
#   6. Prints the launch command
# ============================================================================

set -e

cyan()  { printf "\033[1;36m%s\033[0m\n" "$*"; }
green() { printf "\033[1;32m%s\033[0m\n" "$*"; }
yellow(){ printf "\033[1;33m%s\033[0m\n" "$*"; }
red()   { printf "\033[1;31m%s\033[0m\n" "$*"; }

cyan "================================================================"
cyan "  HELEN OS — WSL2 Ubuntu node bootstrap"
cyan "================================================================"
echo

# ---------------------------------------------------------------- Step 1: bridge
cyan "[1/6] Testing bridge to Windows Ollama..."

OLLAMA_URL=""
if curl -fsS --max-time 3 http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
    OLLAMA_URL="http://127.0.0.1:11434"
    green "  OK via 127.0.0.1 (mirrored networking or localhost forwarding)"
elif curl -fsS --max-time 3 http://host.docker.internal:11434/api/tags >/dev/null 2>&1; then
    OLLAMA_URL="http://host.docker.internal:11434"
    green "  OK via host.docker.internal"
else
    yellow "  127.0.0.1 and host.docker.internal unreachable, trying default-route gateway..."
    HOST_IP=$(ip route show | awk '/default/ {print $3}' | head -1)
    if [ -n "$HOST_IP" ] && curl -fsS --max-time 3 "http://${HOST_IP}:11434/api/tags" >/dev/null 2>&1; then
        OLLAMA_URL="http://${HOST_IP}:11434"
        green "  OK via ${HOST_IP}"
    else
        red   "  BRIDGE FAILED."
        echo
        red   "  Fix on Windows side first:"
        red   "    1. Open PowerShell as Administrator"
        red   "    2. Paste the 5-line block from SETUP_OLLAMA_WIN.bat"
        red   "       (or run that .bat by right-click -> Run as administrator)"
        red   "    3. Re-run this script"
        echo
        red   "  Common cause: OLLAMA_HOST not set to 0.0.0.0:11434, or Windows"
        red   "                Firewall blocking inbound 11434."
        exit 1
    fi
fi

# Verify gemma3:12b is present
if curl -fsS --max-time 3 "${OLLAMA_URL}/api/tags" | grep -q 'gemma3:12b'; then
    green "  gemma3:12b is loaded"
else
    yellow "  WARNING: gemma3:12b not found in /api/tags. Continuing anyway."
    yellow "           Pull it on Windows with:  ollama pull gemma3:12b"
fi
echo

# ---------------------------------------------------------------- Step 2: apt
cyan "[2/6] Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq git python3 python3-venv python3-pip curl tree
green "  OK"
echo

# ---------------------------------------------------------------- Step 3: repo
cyan "[3/6] Cloning helen-conquest repo..."
cd ~
if [ -d helen-conquest/.git ]; then
    yellow "  Repo already exists. Fetching updates..."
    cd helen-conquest
    git fetch --all --quiet
else
    git clone --quiet https://github.com/JMTassy/helen-conquest.git
    cd helen-conquest
fi
green "  OK ($(git rev-parse --short HEAD) on $(git rev-parse --abbrev-ref HEAD))"
echo

# ---------------------------------------------------------------- Step 4: venv
cyan "[4/6] Creating Python virtual environment..."
if [ ! -d .venv ]; then
    python3 -m venv .venv
fi
# shellcheck source=/dev/null
source .venv/bin/activate
pip install --quiet --upgrade pip setuptools wheel
green "  OK ($(python --version))"
echo

# ---------------------------------------------------------------- Step 5: deps
cyan "[5/6] Installing Python dependencies..."
pip install --quiet -r requirements.txt
green "  OK"
echo

# ---------------------------------------------------------------- Step 6: env
cyan "[6/6] Writing HELEN config..."
mkdir -p ~/.helen_os
cat > ~/.helen_os/.env <<EOF
# HELEN OS — generated by SETUP_HELEN_NODE.sh
HELEN_ENVIRONMENT=local
HELEN_PREFER_LOCAL=true
HELEN_DEFAULT_MODEL=gemma3:12b
HELEN_AUTO_FALLBACK=true
HELEN_STREAMING=true
OLLAMA_HOST=${OLLAMA_URL}
EOF
green "  ~/.helen_os/.env written (OLLAMA_HOST=${OLLAMA_URL})"
echo

cyan "================================================================"
green "  BOOTSTRAP COMPLETE"
cyan "================================================================"
echo
echo "Launch HELEN:"
echo
echo "  cd ~/helen-conquest"
echo "  source .venv/bin/activate"
echo "  python helen_unified_interface_v1.py"
echo
echo "Then at the [HELEN] > prompt, try:"
echo "  status"
echo "  models"
echo "  ask Hello, who are you?"
echo
