// jspace_terrain.js — GENERATED by build_jspace_terrain.py. DO NOT EDIT.
// NON_SOVEREIGN · authority=false · ledger_effect=none · surface cannot mark · distance ⊬ admission
window.jspaceTerrain = {
 "authority": false,
 "builder_run_hash": "a4f3f46f76233ece3235540471e9b8a12a03a34e12f4eaa6be523b2be92064c1",
 "canon": false,
 "chain_break": null,
 "chain_verified": true,
 "claim_status": "NO_CLAIM",
 "consumption_log_head_hash": "3d95aea367b8e1f2b3404acd89accb5453a4c41d07c816e5553a7a4a46792816",
 "final": "HOLD_FOR_OPERATOR",
 "frontier": {
  "count": 7,
  "packet_ids": [
   "AR-575d4b83a114",
   "AR-9d167217e823",
   "AR-f7ec3779a583",
   "AR-init-rank-d9c2",
   "AR-promptcomp-e3a1",
   "AR-skill-route-d1f7",
   "AR-sumweights-a8f2"
  ]
 },
 "law": "distance is a rendering, never a mark; distance ⊬ admission; the floor is 1 while the pen is silent; marks happen only via operator_pen.py, never here.",
 "ledger_effect": "none",
 "outbox_snapshot_hash": "677c68fb22aa97aba1ca6309c10a7c13f06a286892592055c898b3f2734c12b8",
 "reducer_required": true,
 "reference_time": "2026-07-17T00:00:00Z",
 "rows": [
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.315434+00:00",
    "decision": "rejected",
    "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9"
   },
   "finding_type": "risk",
   "packet_id": "AR-137a79dbae09",
   "packet_sha256": "a68e6aad60d01449e2ff1dcb47614ee5016b14f577112ef280913b674fa494cd",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.365125+00:00",
    "decision": "rejected",
    "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062"
   },
   "finding_type": "proposal",
   "packet_id": "AR-1c394e006626",
   "packet_sha256": "d51ce5912c759c78b9f8d9d28ac4d9c3b47b0b1b3bd2347dc28a30a2e12936cc",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 13,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:57.380710+00:00",
    "decision": "deferred",
    "entry_hash": "3d95aea367b8e1f2b3404acd89accb5453a4c41d07c816e5553a7a4a46792816"
   },
   "finding_type": "test_gap",
   "packet_id": "AR-1f936d1bda4b",
   "packet_sha256": "8d07b18670863f19b4d4cd724ad50690684b0b19755bffe6cbbf57e14cba78ef",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "0815dc8e1bd6be6f9919b3bc21f1e0136e74c01ef667a2bf5df03dfc2eaecc1a",
     "packet_id": "AR-eee30b74e78d"
    },
    {
     "decision": "deferred",
     "entry_hash": "99b5fc352edca153d0d02c6735d493d49466b58514c6878853f8dfc352a1c1bd",
     "packet_id": "AR-e8d1841c6d2f"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "deferred"
  },
  {
   "age_days": 13,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:57.232233+00:00",
    "decision": "acted",
    "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3"
   },
   "finding_type": "risk",
   "packet_id": "AR-332110575215",
   "packet_sha256": "268f15b6a7d864adf5d78beb6c31da92527e4006ba388c97cdaf6a8aaf905913",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": true,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "acted"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.412308+00:00",
    "decision": "rejected",
    "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6"
   },
   "finding_type": "risk",
   "packet_id": "AR-3521ec730fd4",
   "packet_sha256": "d67cdf30f646fa967aae81b8a5e0fc145f4e2c6ef6db7dea1481fd52dcfb83b9",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.462699+00:00",
    "decision": "rejected",
    "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917"
   },
   "finding_type": "proposal",
   "packet_id": "AR-39307ac76191",
   "packet_sha256": "93a19c426d4ffcd850417bbb52a6ce968e25f8c0e6d2cb66578c92ab566ae10b",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 11,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.509104+00:00",
    "decision": "rejected",
    "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123"
   },
   "finding_type": "risk",
   "packet_id": "AR-3b7799cb88a0",
   "packet_sha256": "1c5e0d23a5a5dd0fd868c044ed694e22244901c78c55b827c11eb81095066005",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.557771+00:00",
    "decision": "rejected",
    "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011"
   },
   "finding_type": "proposal",
   "packet_id": "AR-4eedf96f7ace",
   "packet_sha256": "14829e6aae6fa22d8f7e55f90fd36206af0ca49e42aae642130e6e71183713d7",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.606041+00:00",
    "decision": "rejected",
    "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5"
   },
   "finding_type": "risk",
   "packet_id": "AR-5602a344e0d6",
   "packet_sha256": "d74e74b022aea77e1fb58658768bd6f470901f96d3106736e9d19fe9064af177",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 3,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-575d4b83a114",
   "packet_sha256": "0ab47e300abbf7aa89b3e8da63f7d29b4ca2049939f70e89778448908b8a4907",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.653361+00:00",
    "decision": "rejected",
    "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc"
   },
   "finding_type": "risk",
   "packet_id": "AR-5832a927028e",
   "packet_sha256": "7ae123e1ce2a71b7b73633bd968597a2197c553b8889bd2768c8ced2e53c48ef",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.705144+00:00",
    "decision": "rejected",
    "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d"
   },
   "finding_type": "proposal",
   "packet_id": "AR-603402e9d1c4",
   "packet_sha256": "72250aaa51216a7028c5585fddad2d857ceb08c4642e8585fa31951629e5e24e",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.752264+00:00",
    "decision": "rejected",
    "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd"
   },
   "finding_type": "risk",
   "packet_id": "AR-622d76f69257",
   "packet_sha256": "f512693f821626e7ed1c7114ac00de888c953a2bdd05b90aeb8dd2300e864c6c",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.802397+00:00",
    "decision": "rejected",
    "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e"
   },
   "finding_type": "proposal",
   "packet_id": "AR-671223d898a2",
   "packet_sha256": "726f6cc59930923966037479c93a6c826bb23fd0335ca4fd079999cab4447b52",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.851888+00:00",
    "decision": "rejected",
    "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d"
   },
   "finding_type": "proposal",
   "packet_id": "AR-83d2c37481c7",
   "packet_sha256": "9a707b63c2d2224d0c7c9864d85af90a4cab20650e491300c96d8578d2ee800f",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.900958+00:00",
    "decision": "rejected",
    "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043"
   },
   "finding_type": "proposal",
   "packet_id": "AR-842e7f4922cf",
   "packet_sha256": "0d30e03ea88671aad34942bb7a135af39141aaa80b108fc641f8ccdd894351c1",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:45.950916+00:00",
    "decision": "rejected",
    "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488"
   },
   "finding_type": "risk",
   "packet_id": "AR-941d3bbb6333",
   "packet_sha256": "78cf069f29f073c8b9f030ad0f71048e46af493d6a2d697b1c8556a9aaa103b6",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 11,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.000524+00:00",
    "decision": "rejected",
    "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30"
   },
   "finding_type": "risk",
   "packet_id": "AR-944b83d2fa9e",
   "packet_sha256": "f7168a05f58f424a44d86132f432417a1ed39d85f353b2882ef5dae295f35077",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.049540+00:00",
    "decision": "rejected",
    "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97"
   },
   "finding_type": "proposal",
   "packet_id": "AR-9598791758a5",
   "packet_sha256": "3815adff1a90201dac5471e6fac572f2a5f0416d6448affbb516f15ed51075ba",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 4,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-9d167217e823",
   "packet_sha256": "34f05e24f0f0b7ed44c1dab11e2ebb96a4bbe7c25dd031a5fb24b1755ac10073",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.101504+00:00",
    "decision": "rejected",
    "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a"
   },
   "finding_type": "risk",
   "packet_id": "AR-a657ef5764d8",
   "packet_sha256": "a8a99ac898a09dfed6042c56c286d4966854c7290e6fdeb87f09416d295fc213",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.157548+00:00",
    "decision": "rejected",
    "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f"
   },
   "finding_type": "proposal",
   "packet_id": "AR-b634eae985b4",
   "packet_sha256": "794a8dd423243288c3f0206ef20c0b2e0ac184954b30f9c13fd83266c0387b2d",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.208705+00:00",
    "decision": "rejected",
    "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508"
   },
   "finding_type": "risk",
   "packet_id": "AR-c1f03861ffdc",
   "packet_sha256": "f3c357953d1bc592ceff1ae390504d29c3b920d8df1d2b58c68f08427145547b",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.260350+00:00",
    "decision": "rejected",
    "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8"
   },
   "finding_type": "risk",
   "packet_id": "AR-c73a8b88fb8d",
   "packet_sha256": "cba2c71b96a6cefad09cb2ee1a3f4c60efe75ee0fcc74c0019e4ff0e0ebde8bf",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.319116+00:00",
    "decision": "rejected",
    "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2"
   },
   "finding_type": "proposal",
   "packet_id": "AR-c8121dc0789e",
   "packet_sha256": "7cd890abc03b73e4ee8410556e4b31bb081574fcea91b08f4ba7670cfecf4612",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 11,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T01:13:50.531337+00:00",
    "decision": "acted",
    "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699"
   },
   "finding_type": "risk",
   "packet_id": "AR-cecf4c5b553f",
   "packet_sha256": "eeade882a5c2b269569b7c14033ef5f00fb092fcb3e66ab78af5181d2497cca4",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": true,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "acted"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.411180+00:00",
    "decision": "rejected",
    "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d"
   },
   "finding_type": "proposal",
   "packet_id": "AR-cfad921197fc",
   "packet_sha256": "7cb64a8ad6b87d02854e40b86280bfd322aec502f29452b16f13a82acecdcc66",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.480358+00:00",
    "decision": "rejected",
    "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd"
   },
   "finding_type": "proposal",
   "packet_id": "AR-d30a1396bd93",
   "packet_sha256": "092c2a2e7c8cfa4dde43bb33f5bb304d0ed8c9e0ffb30fd09674a54d36c811e5",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0",
     "packet_id": "AR-ed9bd849fb7e"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 11,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:57.330085+00:00",
    "decision": "deferred",
    "entry_hash": "99b5fc352edca153d0d02c6735d493d49466b58514c6878853f8dfc352a1c1bd"
   },
   "finding_type": "test_gap",
   "packet_id": "AR-e8d1841c6d2f",
   "packet_sha256": "f07c816a4bd99a411aab89f545f8d8934827bb6aa18e7186e17402528185d3a2",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "0815dc8e1bd6be6f9919b3bc21f1e0136e74c01ef667a2bf5df03dfc2eaecc1a",
     "packet_id": "AR-eee30b74e78d"
    },
    {
     "decision": "deferred",
     "entry_hash": "3d95aea367b8e1f2b3404acd89accb5453a4c41d07c816e5553a7a4a46792816",
     "packet_id": "AR-1f936d1bda4b"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "deferred"
  },
  {
   "age_days": 11,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.529764+00:00",
    "decision": "rejected",
    "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26"
   },
   "finding_type": "risk",
   "packet_id": "AR-ea91f2b2230c",
   "packet_sha256": "8a07c188f0e8ad4d2fcac68e671e1ca04962834e94e5db7f5e0cd45700b243d0",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71",
     "packet_id": "AR-eec73bbbf239"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.583984+00:00",
    "decision": "rejected",
    "entry_hash": "a8f3ad30db502b8816aed0746a583bae2e6da9abde7dd3f8fb26a62dc8afc9f0"
   },
   "finding_type": "proposal",
   "packet_id": "AR-ed9bd849fb7e",
   "packet_sha256": "83c9ed39870c60e6bc7a3c3bcae18e9ea7bfa47209bdd3d9783fb7b90e9abc2f",
   "precedent_marks": [
    {
     "decision": "rejected",
     "entry_hash": "367673f74cc7503df5c2ae2002a730f450edbb5e1ff5cf98778eb167019b9062",
     "packet_id": "AR-1c394e006626"
    },
    {
     "decision": "rejected",
     "entry_hash": "e1f4c40559c04965ad6bcedc800dc09c3268c0eac00ffb511b0d00380f030917",
     "packet_id": "AR-39307ac76191"
    },
    {
     "decision": "rejected",
     "entry_hash": "f0848d90df8bf84a25a402b9f3dafa7093be789e6c323eb1f248f1abf8126011",
     "packet_id": "AR-4eedf96f7ace"
    },
    {
     "decision": "rejected",
     "entry_hash": "b166c114fee5fa034abcd61945dc3dd8afd4c0aecfcfc41b0a0e46f78f4f4f4d",
     "packet_id": "AR-603402e9d1c4"
    },
    {
     "decision": "rejected",
     "entry_hash": "addc1a337feff46a92f93101fd289c3a22c544cd7c470e80416abe0f724bd59e",
     "packet_id": "AR-671223d898a2"
    },
    {
     "decision": "rejected",
     "entry_hash": "b455f3864daecbbce811eea93727d58a59ad6094917f0eee69e7f0a643ab5b8d",
     "packet_id": "AR-83d2c37481c7"
    },
    {
     "decision": "rejected",
     "entry_hash": "1afa2bc57da53391bc461f8ecc4dce3358a3fbd764612232f9cc54d537d80043",
     "packet_id": "AR-842e7f4922cf"
    },
    {
     "decision": "rejected",
     "entry_hash": "ecebdd31b0c13d86421c246bb345c30fb862a195f8b81a42f9d3e5d56a3bbb97",
     "packet_id": "AR-9598791758a5"
    },
    {
     "decision": "rejected",
     "entry_hash": "eeb4c3360c9182fe3f875841f04e55ee28b9de050645685eae30cb0fbe43524f",
     "packet_id": "AR-b634eae985b4"
    },
    {
     "decision": "rejected",
     "entry_hash": "cb5a861c1c7480d5d2af3245663dcdd936dbbd671f836f60a56fd058e491c2f2",
     "packet_id": "AR-c8121dc0789e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3edb63a87f35b54a324f6a96bd69523222946c267fa43307606da56ca806732d",
     "packet_id": "AR-cfad921197fc"
    },
    {
     "decision": "rejected",
     "entry_hash": "502fa1fa4e4198d6b70081512c16a4b015fbbc527464b48a5e4ea68d55360dfd",
     "packet_id": "AR-d30a1396bd93"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 26,
   "distance": 1,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:46.634007+00:00",
    "decision": "rejected",
    "entry_hash": "318dacdc3c08c1e4b2acb5db4ece1262f156371e24f695e7f86c868ea5128a71"
   },
   "finding_type": "risk",
   "packet_id": "AR-eec73bbbf239",
   "packet_sha256": "ab1a4e3cc7fc3cb59df960c78c03447c0df0ddf312fdb1394fdfe378df29cd6a",
   "precedent_marks": [
    {
     "decision": "acted",
     "entry_hash": "64f245f24dd8cb39bc516ee01446e3c2869011a6e06e6a57b662cdbe97393699",
     "packet_id": "AR-cecf4c5b553f"
    },
    {
     "decision": "rejected",
     "entry_hash": "8e043b1b83ec71b1c7ef266a04f7eee751bab7ad0c6894dd877aedda2c6b8aa9",
     "packet_id": "AR-137a79dbae09"
    },
    {
     "decision": "rejected",
     "entry_hash": "6bbd7b598d75891879d31e7ef1e2d1d02f3242a4f245894d47f6905d28e4cdc6",
     "packet_id": "AR-3521ec730fd4"
    },
    {
     "decision": "rejected",
     "entry_hash": "df5c25e6cada5ccf265c71d429502dc07718f55cf198cac0b49c422bb45b8123",
     "packet_id": "AR-3b7799cb88a0"
    },
    {
     "decision": "rejected",
     "entry_hash": "587aafd650c5725c48ef9327e2d97b6f6053fc9393345651ce6a50ca02b55ab5",
     "packet_id": "AR-5602a344e0d6"
    },
    {
     "decision": "rejected",
     "entry_hash": "96e4c3bf3bd52c4c1d6a7ab345d38d655e2e705ba2683ee2edbe74bc86af26fc",
     "packet_id": "AR-5832a927028e"
    },
    {
     "decision": "rejected",
     "entry_hash": "5cb19e5d150cfff2b1f4d3eb4a910ccdb80ae56945b5e4ee79e9ea9ebe5e20cd",
     "packet_id": "AR-622d76f69257"
    },
    {
     "decision": "rejected",
     "entry_hash": "b3fb3cd61850c5a854fe7371329424c88efe427a3ff29b8e4249aee1fd138488",
     "packet_id": "AR-941d3bbb6333"
    },
    {
     "decision": "rejected",
     "entry_hash": "3d8a8bc958972aafea3a9e1250b787de4cce3ef30c6d2e9806d50bcc67a52c30",
     "packet_id": "AR-944b83d2fa9e"
    },
    {
     "decision": "rejected",
     "entry_hash": "3291e34b1e794ea8457f1c165a025ac0eb96e08b5437391b21b890c318150c5a",
     "packet_id": "AR-a657ef5764d8"
    },
    {
     "decision": "rejected",
     "entry_hash": "40d1ed08f7ea9ca56f9f2848837ab33d51d5b0da9e534eef10f3a637e01e9508",
     "packet_id": "AR-c1f03861ffdc"
    },
    {
     "decision": "rejected",
     "entry_hash": "9b547e2791fe54ee723dde1f47a4c24e39cc90eb8a9f9106c1e95f97c4e5aaf8",
     "packet_id": "AR-c73a8b88fb8d"
    },
    {
     "decision": "rejected",
     "entry_hash": "167f17e3add744d4272e87e056ed67f54f25011481e1b27334435f0041404c26",
     "packet_id": "AR-ea91f2b2230c"
    },
    {
     "decision": "acted",
     "entry_hash": "5585fa17eb4cabae989aa69b974ab435e5dc97edcf6cfc916286f4691aae78b3",
     "packet_id": "AR-332110575215"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "rejected"
  },
  {
   "age_days": 13,
   "distance": 0,
   "effective_operator_decision": {
    "at": "2026-07-06T10:16:57.279978+00:00",
    "decision": "acted",
    "entry_hash": "0815dc8e1bd6be6f9919b3bc21f1e0136e74c01ef667a2bf5df03dfc2eaecc1a"
   },
   "finding_type": "test_gap",
   "packet_id": "AR-eee30b74e78d",
   "packet_sha256": "cadc065703494b23e647e38edb345ec54162ccb3f075bba604c4cd9d8bb24f40",
   "precedent_marks": [
    {
     "decision": "deferred",
     "entry_hash": "99b5fc352edca153d0d02c6735d493d49466b58514c6878853f8dfc352a1c1bd",
     "packet_id": "AR-e8d1841c6d2f"
    },
    {
     "decision": "deferred",
     "entry_hash": "3d95aea367b8e1f2b3404acd89accb5453a4c41d07c816e5553a7a4a46792816",
     "packet_id": "AR-1f936d1bda4b"
    }
   ],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": true,
     "obligation": "risk_flags_cleared"
    }
   ],
   "state": "acted"
  },
  {
   "age_days": 4,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-f7ec3779a583",
   "packet_sha256": "1b98ca7ede54fd38c97ca069cc4fbc0151cb838c4769d7eedc8c0253831982c4",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": null,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-init-rank-d9c2",
   "packet_sha256": "412ddae2cb8a8b8a06be9bb5697619efc0b1a5a0d9c6eef6c02024ec4ca9f330",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": null,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-promptcomp-e3a1",
   "packet_sha256": "84f43775f7be8d343e45c259b021f2887bc9ada34e49a41917e9829ac818d105",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": 0,
   "distance": 2,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-skill-route-d1f7",
   "packet_sha256": "47af96015bcddd756b39da93753d1e36e7e849e723ac0fd844dabcff12b50e00",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "gate PASS ⊬ admission",
     "met": false,
     "obligation": "risk_flags_cleared"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  },
  {
   "age_days": null,
   "distance": 1,
   "effective_operator_decision": null,
   "finding_type": "gap",
   "packet_id": "AR-sumweights-a8f2",
   "packet_sha256": "39534939f20629377dba37f86efbc362ad8b8e048fa8712ac518b431619cedb9",
   "precedent_marks": [],
   "remaining_obligations": [
    {
     "cites": "NO HASH = NO VOICE",
     "met": true,
     "obligation": "readable"
    },
    {
     "cites": "JM decision ⊢ admin reality",
     "met": false,
     "obligation": "operator_decision"
    }
   ],
   "state": "unjudged"
  }
 ],
 "schema": "MEMBRANE_DISTANCE_WITNESS_V0",
 "sovereign": false,
 "surface_can_mark": false
};
