// warren_home_data.js — GENERATED by build_warren_home.py. DO NOT EDIT.
// NON_SOVEREIGN · authority=false · ledger_effect=none · surface cannot mark · dream ⊬ admission
window.WARREN_HOME = {
 "authority": false,
 "canon": false,
 "carnet": [
  {
   "at": "2026-07-06T10:16:57.380710+00:00",
   "decision": "deferred",
   "note": "queue after garden-validators-CI: unit tests for helen_sandbox_agent_adapter",
   "packet_id": "AR-1f936d1bda4b"
  },
  {
   "at": "2026-07-06T10:16:57.330085+00:00",
   "decision": "deferred",
   "note": "needs operator ruling: regenerate runs/ fixtures vs descope VERIFY_ALL steps 3-4",
   "packet_id": "AR-e8d1841c6d2f"
  },
  {
   "at": "2026-07-06T10:16:57.279978+00:00",
   "decision": "acted",
   "note": "bounded task queued: wire 4 garden validators into CI workflow",
   "packet_id": "AR-eee30b74e78d"
  },
  {
   "at": "2026-07-06T10:16:57.232233+00:00",
   "decision": "acted",
   "note": "consumption organ built+tested (triage/pen/guard, 30 tests); this card is the requested workflow",
   "packet_id": "AR-332110575215"
  },
  {
   "at": "2026-07-06T10:16:46.634007+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-eec73bbbf239"
  },
  {
   "at": "2026-07-06T10:16:46.583984+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-ed9bd849fb7e"
  },
  {
   "at": "2026-07-06T10:16:46.529764+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-ea91f2b2230c"
  },
  {
   "at": "2026-07-06T10:16:46.480358+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-d30a1396bd93"
  }
 ],
 "day": {
  "counts": {
   "acted": 3,
   "deferred": 2,
   "rejected": 26
  },
  "marks_total": 31
 },
 "dreams": [
  {
   "finding_type": "gap",
   "packet_id": "AR-575d4b83a114",
   "severity": "info",
   "title": "No deduplication, no cap, no ranking on capability_gaps before prompt in"
  },
  {
   "finding_type": "gap",
   "packet_id": "AR-9d167217e823",
   "severity": "info",
   "title": "Quality score is binary in practice: 0.0 (invalid) or 1.0 (any non-empty"
  },
  {
   "finding_type": "gap",
   "packet_id": "AR-f7ec3779a583",
   "severity": "info",
   "title": "Unbounded history in helen.py:speak()—"
  },
  {
   "finding_type": "gap",
   "packet_id": "AR-init-rank-d9c2",
   "severity": "info",
   "title": "init_helen_wedge.py:_top_threads() collects last_updated per thread (lin"
  },
  {
   "finding_type": "gap",
   "packet_id": "AR-promptcomp-e3a1",
   "severity": "info",
   "title": "Prior packet AR-f7ec3779a583 proposed tail=20 at helen.py:speak() only"
  },
  {
   "finding_type": "gap",
   "packet_id": "AR-sumweights-a8f2",
   "severity": "info",
   "title": "Four scoring bands (1.0 / 0.75 / 0.5 / 0.0) with threshold at 0.5 mean t"
  }
 ],
 "histoire": [
  {
   "at": "2026-07-06T01:13:50.531337+00:00",
   "decision": "acted",
   "note": "JM GO 2026-07-06: 3 writers allowlisted in kernel_guard.sh CONSUMER_ALLOWLIST; guard re-run PASS 0 violations",
   "packet_id": "AR-cecf4c5b553f"
  },
  {
   "at": "2026-07-06T10:16:45.315434+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-137a79dbae09"
  },
  {
   "at": "2026-07-06T10:16:45.365125+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-1c394e006626"
  },
  {
   "at": "2026-07-06T10:16:45.412308+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-3521ec730fd4"
  },
  {
   "at": "2026-07-06T10:16:45.462699+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-39307ac76191"
  },
  {
   "at": "2026-07-06T10:16:45.509104+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-3b7799cb88a0"
  },
  {
   "at": "2026-07-06T10:16:45.557771+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-4eedf96f7ace"
  },
  {
   "at": "2026-07-06T10:16:45.606041+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-5602a344e0d6"
  },
  {
   "at": "2026-07-06T10:16:45.653361+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-5832a927028e"
  },
  {
   "at": "2026-07-06T10:16:45.705144+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-603402e9d1c4"
  },
  {
   "at": "2026-07-06T10:16:45.752264+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-622d76f69257"
  },
  {
   "at": "2026-07-06T10:16:45.802397+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-671223d898a2"
  },
  {
   "at": "2026-07-06T10:16:45.851888+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-83d2c37481c7"
  },
  {
   "at": "2026-07-06T10:16:45.900958+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-842e7f4922cf"
  },
  {
   "at": "2026-07-06T10:16:45.950916+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-941d3bbb6333"
  },
  {
   "at": "2026-07-06T10:16:46.000524+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-944b83d2fa9e"
  },
  {
   "at": "2026-07-06T10:16:46.049540+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-9598791758a5"
  },
  {
   "at": "2026-07-06T10:16:46.101504+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-a657ef5764d8"
  },
  {
   "at": "2026-07-06T10:16:46.157548+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-b634eae985b4"
  },
  {
   "at": "2026-07-06T10:16:46.208705+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-c1f03861ffdc"
  },
  {
   "at": "2026-07-06T10:16:46.260350+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-c73a8b88fb8d"
  },
  {
   "at": "2026-07-06T10:16:46.319116+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-c8121dc0789e"
  },
  {
   "at": "2026-07-06T10:16:46.411180+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-cfad921197fc"
  },
  {
   "at": "2026-07-06T10:16:46.480358+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-d30a1396bd93"
  },
  {
   "at": "2026-07-06T10:16:46.529764+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-ea91f2b2230c"
  },
  {
   "at": "2026-07-06T10:16:46.583984+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-ed9bd849fb7e"
  },
  {
   "at": "2026-07-06T10:16:46.634007+00:00",
   "decision": "rejected",
   "note": "lexical marker noise: keyword flags in proposal docs, no crossing analysis; upgrade scanner to crossing-detect",
   "packet_id": "AR-eec73bbbf239"
  },
  {
   "at": "2026-07-06T10:16:57.232233+00:00",
   "decision": "acted",
   "note": "consumption organ built+tested (triage/pen/guard, 30 tests); this card is the requested workflow",
   "packet_id": "AR-332110575215"
  },
  {
   "at": "2026-07-06T10:16:57.279978+00:00",
   "decision": "acted",
   "note": "bounded task queued: wire 4 garden validators into CI workflow",
   "packet_id": "AR-eee30b74e78d"
  },
  {
   "at": "2026-07-06T10:16:57.330085+00:00",
   "decision": "deferred",
   "note": "needs operator ruling: regenerate runs/ fixtures vs descope VERIFY_ALL steps 3-4",
   "packet_id": "AR-e8d1841c6d2f"
  },
  {
   "at": "2026-07-06T10:16:57.380710+00:00",
   "decision": "deferred",
   "note": "queue after garden-validators-CI: unit tests for helen_sandbox_agent_adapter",
   "packet_id": "AR-1f936d1bda4b"
  }
 ],
 "law": "Les Gobelins rêvent. Vous décidez. — dream shown ⊬ dream admitted; meters are renderings of state, never state itself; marks happen only via operator_pen.py, never here.",
 "ledger_effect": "none",
 "meters": {
  "confiance": 82,
  "danger": 60,
  "ferraille": 26,
  "humeur": 60,
  "nourriture": 44,
  "reves_badge": 6
 },
 "pen_chain": "intact",
 "schema": "WARREN_HOME_DATA_V1",
 "skipped": [],
 "sovereign": false,
 "start_day_command": "python3 temple/autoresearch/autoresearch_scanner.py --input-dir docs/proposals   # dry-run; crossings arrive as dreams",
 "surface_can_mark": false
};
