"""
BRF_COUNTER: Counter-Analytical Brief Job
===========================================

Single rival perspective on the main brief.
Identifies strongest counter-argument, top falsifiers, missing evidence.

K2 invariant: Counter generated by different module (not BRF_ONEPAGER).
Authority stays single; rivalry stays in Labor.
"""

import json
import hashlib
from dataclasses import dataclass, asdict
from typing import List, Dict, Any
from datetime import datetime


@dataclass
class CounterAnalysis:
    """Structured counter-narrative."""
    counter_bet: str  # The opposite claim (≤100 chars, same format as ONE BET)
    confidence: float  # 0.0-1.0: how strong is this counter?
    top_3_falsifiers: List[str]  # What evidence would prove main brief wrong
    missing_evidence: List[str]  # Critical data not yet gathered
    reasoning: str  # Why this counter is credible
    probability_estimate: float  # If we gathered missing evidence, % chance main brief reverses?


def generate_counter(
    main_brief: Dict[str, Any],
    clusters: List[Dict[str, Any]],
) -> CounterAnalysis:
    """
    Generate a counter-narrative to the main brief.

    Args:
        main_brief: Output from BRF_ONEPAGER (contains "one_bet" + reasoning)
        clusters: Theme clusters from INS_CLUSTER

    Returns:
        CounterAnalysis with counter-bet, falsifiers, missing evidence
    """

    main_bet = main_brief.get("one_bet", "")
    main_reasoning = main_brief.get("reasoning", "")

    # Simple but deterministic inversion logic
    # (In production, use LLM for generation, deterministic for structure)

    counter_bet = invert_bet(main_bet)
    falsifiers = extract_falsifiers(main_reasoning, clusters)
    missing = identify_missing_evidence(clusters)

    confidence = estimate_confidence(main_reasoning, falsifiers)
    probability = estimate_reversal_probability(confidence, len(missing))

    return CounterAnalysis(
        counter_bet=counter_bet,
        confidence=confidence,
        top_3_falsifiers=falsifiers[:3],
        missing_evidence=missing[:3],
        reasoning=f"Counter to: {main_bet}. Confidence: {confidence:.1%}",
        probability_estimate=probability,
    )


def invert_bet(bet: str) -> str:
    """
    Simple inversion of main bet.

    Examples:
    "Approve skill X" → "Reject skill X until more evidence"
    "High urgency" → "Low urgency; wait for data"
    """
    if not bet:
        return "No action; wait for more evidence"

    # Deterministic prefix inversion
    if bet.lower().startswith(("approve", "accept", "enable", "proceed")):
        return f"Reject until verified: {bet[8:]}"
    elif bet.lower().startswith(("reject", "decline", "disable")):
        return f"Approve conditionally: {bet[7:]}"
    else:
        return f"Opposite: {bet}"


def extract_falsifiers(reasoning: str, clusters: List[Dict]) -> List[str]:
    """
    Extract claims from main brief that could be disproven.

    Returns top things that, if false, would reverse the recommendation.
    """
    falsifiers = []

    # If reasoning mentions "safe", falsifier is "not safe"
    if "safe" in reasoning.lower():
        falsifiers.append("Security scan reveals vulnerabilities")

    if "tested" in reasoning.lower():
        falsifiers.append("Tests fail under production load")

    if "urgent" in reasoning.lower():
        falsifiers.append("Deadline is not actually critical")

    if "precedent" in reasoning.lower():
        falsifiers.append("Historical analogs actually failed")

    # Add cluster-based falsifiers
    for cluster in clusters[:2]:
        theme = cluster.get("theme", "")
        if theme:
            falsifiers.append(f"Cluster '{theme}' contradicts assumption")

    return falsifiers[:5]


def identify_missing_evidence(clusters: List[Dict]) -> List[str]:
    """
    What data would strengthen or weaken the brief?
    """
    missing = [
        "Performance metrics under production load",
        "Security audit from independent team",
        "Historical outcomes of similar decisions",
        "Stakeholder feedback (not yet collected)",
        "Risk assessment from domain experts",
    ]

    # Remove evidence types already in clusters
    cluster_themes = {c.get("theme", "").lower() for c in clusters}

    return [m for m in missing if m.lower() not in cluster_themes][:5]


def estimate_confidence(reasoning: str, falsifiers: List[str]) -> float:
    """
    How strong is the counter-narrative?
    More falsifiers = higher confidence in counter.
    """
    base = 0.3  # Counter always has some plausibility
    falsifier_boost = min(len(falsifiers) * 0.15, 0.4)
    return min(base + falsifier_boost, 0.95)


def estimate_reversal_probability(
    counter_confidence: float,
    missing_evidence_count: int,
) -> float:
    """
    If we gathered all missing evidence, what's the probability
    the brief recommendation reverses?
    """
    # More missing evidence = higher chance brief was wrong
    missing_impact = min(missing_evidence_count * 0.2, 0.5)
    return min(counter_confidence + missing_impact, 0.9)


def hash_counter(counter: CounterAnalysis) -> str:
    """Deterministic hash of counter for immutability."""
    serialized = json.dumps(asdict(counter), sort_keys=True)
    return hashlib.sha256(serialized.encode()).hexdigest()[:16]


def generate_claim_from_counter(
    brief_id: str,
    counter: CounterAnalysis,
    evidence_hash: str = "",
) -> Dict[str, Any]:
    """
    Convert counter-analysis into a claim that TRI can evaluate.

    The claim says: "Consider this counter-narrative before accepting main brief."
    """
    return {
        "claim_type": "counter_analysis",
        "parent_brief_id": brief_id,
        "counter_bet": counter.counter_bet,
        "confidence": counter.confidence,
        "probability_reversal": counter.probability_estimate,
        "falsifiers": counter.top_3_falsifiers,
        "missing_evidence": counter.missing_evidence,
        "evidence_pointer": evidence_hash,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "counter_hash": hash_counter(counter),
    }


def main():
    """Example: generate counter-analysis."""
    print("=" * 60)
    print("BRF_COUNTER: Counter-Analytical Brief Generator")
    print("=" * 60)

    # Example brief from BRF_ONEPAGER
    example_brief = {
        "one_bet": "Approve Moltbook skill integration",
        "reasoning": (
            "Moltbook has tested integration, safe API, urgent deadline. "
            "Precedent: similar integrations succeeded."
        ),
    }

    # Example clusters from INS_CLUSTER
    example_clusters = [
        {"theme": "Security", "weight": 0.6},
        {"theme": "Performance", "weight": 0.4},
    ]

    print("\n📋 Main Brief:")
    print(f"  ONE BET: {example_brief['one_bet']}")
    print(f"  Reasoning: {example_brief['reasoning']}")

    counter = generate_counter(example_brief, example_clusters)

    print("\n⚡ Counter-Analysis:")
    print(f"  Counter BET: {counter.counter_bet}")
    print(f"  Confidence: {counter.confidence:.0%}")
    print(f"  Top 3 Falsifiers:")
    for f in counter.top_3_falsifiers:
        print(f"    • {f}")
    print(f"  Missing Evidence:")
    for m in counter.missing_evidence:
        print(f"    • {m}")
    print(f"  Reversal Probability: {counter.probability_estimate:.0%}")

    print("\n📌 Claim Generated:")
    claim = generate_claim_from_counter(
        brief_id="brief_example_001",
        counter=counter,
    )
    print(json.dumps(claim, indent=2))

    print("\n✓ Counter-analysis complete")


if __name__ == "__main__":
    main()
