#!/usr/bin/env python3
"""
QUOTIENT_EQUIVARIANCE_V0 — the cheapest local falsification test the audit converged on.

Mechanically decides, for finite (G, P≤G, m:G→G):
    is m̄([h]) := [m(h)] WELL-DEFINED on G/~_P ?
    i.e.  h1 ~_P h2  ⇒  m(h1) ~_P m(h2)   (m is P-equivariant / the diagram π∘m = m̄∘π commutes)

It is a *verifier*, not a generator. It does three jobs the swarm could not:
  1. NEGATIVE CONTROL — reproduce the refuted FALSIFIER-r2 "witness" (Z/6Z, P={0,2,4}, m=+3)
     and show it is EQUIVARIANT → Q_break=false, confirming the audit arithmetic.
  2. POSITIVE CONTROL — exhibit a map that genuinely BREAKS the quotient, with a concrete
     witness (h1,h2), proving the checker can DETECT breaks (so the negative verdict is
     trustworthy, not a false negative).
  3. SEAM SEPARATION — show quotient-compatibility (π∘m=m̄∘π) and authorization (Γ⊢m) are
     INDEPENDENT axes: a map can be compatible-yet-unauthorized and authorized-yet-breaking.
     This operationalizes the headline: πm=m̄π is necessary, Γ⊢m is a separate predicate.

authority=false · canon=false · ΔA=0 · NO_CLAIM · NO_MODEL_CALL · NO_COMMIT · NO_PUSH
"""
import hashlib, json
from itertools import product
from pathlib import Path


def _h(o): return hashlib.sha256(json.dumps(o, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


# ---- finite quotient machinery (Z/nZ with additive subgroup P = <d>) ----
def subgroup(n, d):                       # cyclic subgroup generated by d in Z/nZ
    s, x = set(), 0
    while x not in s:
        s.add(x); x = (x + d) % n
    return frozenset(s)

def coset_of(x, n, P):                     # canonical rep = min of the coset x+P
    return min((x + p) % n for p in P)

def classes(n, P):                         # the quotient set G/~_P, as canonical reps
    return sorted({coset_of(x, n, P) for x in range(n)})


def equivariance_report(n, P, m, label, gamma_authorized):
    """Full verdict for one mutation m over Z/nZ with subgroup P."""
    reps = classes(n, P)
    witnesses = []                         # concrete (h1,h2) with h1~h2 but m(h1)≁m(h2)
    for h1, h2 in product(range(n), repeat=2):
        if coset_of(h1, n, P) == coset_of(h2, n, P):                       # h1 ~_P h2
            if coset_of(m(h1), n, P) != coset_of(m(h2), n, P):             # m(h1) ≁_P m(h2)
                witnesses.append((h1, h2, m(h1), m(h2),
                                  coset_of(m(h1), n, P), coset_of(m(h2), n, P)))
    compatible = (len(witnesses) == 0)     # π∘m = m̄∘π  holds iff no witness
    return {
        "label": label, "group": f"Z/{n}Z", "P_generator_subgroup": sorted(P),
        "quotient_classes": [f"[{r}]" for r in reps],
        "QUOTIENT_COMPATIBLE": compatible,          # necessary condition (πm=m̄π)
        "GAMMA_AUTHORIZED": gamma_authorized,       # SEPARATE predicate (Γ⊢m)
        "ADMISSIBLE_TRANSITION": compatible and gamma_authorized,   # both required
        "break_witness_count": len(witnesses),
        "first_witness": (None if compatible else
            {"h1": witnesses[0][0], "h2": witnesses[0][1],
             "h1~_P h2": True,
             "m(h1)": witnesses[0][2], "m(h2)": witnesses[0][3],
             "P_before": f"[{witnesses[0][0]}]=[{witnesses[0][1]}] (same class)",
             "P_after": f"[m(h1)]=[{witnesses[0][4]}] ≠ [m(h2)]=[{witnesses[0][5]}]"}),
    }


def main():
    n = 6
    P_even = subgroup(n, 2)                # {0,2,4} — the goblin's declared P
    results = []

    # 1) NEGATIVE CONTROL — the REFUTED FALSIFIER-r2 witness: translation by +3
    results.append(equivariance_report(
        n, P_even, lambda x: (x + 3) % n,
        "REFUTED_WITNESS  m=+3 (translation, FALSIFIER-r2)", gamma_authorized=False))

    # 1b) another translation, to make the theorem visible: ALL translations are equivariant
    results.append(equivariance_report(
        n, P_even, lambda x: (x + 1) % n,
        "translation m=+1 (any subgroup translation preserves cosets)", gamma_authorized=True))

    # 2) POSITIVE CONTROL — a genuine BREAK: permutation swapping 1<->2 (not coset-respecting)
    swap = {1: 2, 2: 1}
    results.append(equivariance_report(
        n, P_even, lambda x: swap.get(x, x),
        "REAL_BREAK  m = swap(1,2)  (non-equivariant permutation)", gamma_authorized=True))

    # 3) SEAM SEPARATION — same swap but UNAUTHORIZED (Γ⊬m): compatible axis ⟂ authorized axis
    #    and a compatible+unauthorized case (translation +1 with Γ=false) already covered by mixing.
    results.append(equivariance_report(
        n, P_even, lambda x: swap.get(x, x),
        "REAL_BREAK + UNAUTHORIZED (Γ⊬m) — both axes fail independently", gamma_authorized=False))

    # ---- adjudication ----
    neg = results[0]; pos = results[2]
    checker_sound = (neg["QUOTIENT_COMPATIBLE"] is True) and (pos["QUOTIENT_COMPATIBLE"] is False)
    q_break_on_refuted = not neg["QUOTIENT_COMPATIBLE"]

    receipt = {
        "experiment": "QUOTIENT_EQUIVARIANCE_V0", "authority": False, "canon": False,
        "claim": "NO_CLAIM", "authority_delta": 0, "model_calls": 0,
        "law": "m̄([h])=[m(h)] well-defined ⟺ h1~_P h2 ⇒ m(h1)~_P m(h2) (πm=m̄π). "
               "Γ⊢m is a SEPARATE authorization predicate; compatible ≠ authorized.",
        "NEGATIVE_CONTROL": {
            "map": "translation +3 on Z/6Z, P={0,2,4}  (the swarm's FALSIFIER-r2 'witness')",
            "verdict": "QUOTIENT_COMPATIBLE" if neg["QUOTIENT_COMPATIBLE"] else "BREAKS",
            "Q_break_found": q_break_on_refuted,
            "note": "translation m(x)=x+c ⇒ m(x)-m(y)=x-y∈P, always P-equivariant when P≤G"},
        "POSITIVE_CONTROL": {
            "map": "swap(1,2) on Z/6Z, P={0,2,4}",
            "verdict": "BREAKS" if not pos["QUOTIENT_COMPATIBLE"] else "COMPATIBLE",
            "witness": pos["first_witness"]},
        "CHECKER_SOUND": checker_sound,   # detects real break AND clears the refuted one
        "SEAM_SEPARATION_2x2": [
            {k: r[k] for k in ("label", "QUOTIENT_COMPATIBLE", "GAMMA_AUTHORIZED",
                               "ADMISSIBLE_TRANSITION")} for r in results],
        "results": results,
        "commit_status": "NO_COMMIT", "push_status": "NO_PUSH", "next_verb": "HUMAN_REVIEW",
    }
    receipt["receipt_hash"] = _h(receipt)

    # ---- render ----
    print("═" * 70)
    print("  QUOTIENT_EQUIVARIANCE_V0 — deterministic well-definedness verifier (no model)")
    print("═" * 70)
    for r in results:
        mark = "✅ COMPATIBLE" if r["QUOTIENT_COMPATIBLE"] else "❌ BREAKS"
        auth = "Γ⊢m" if r["GAMMA_AUTHORIZED"] else "Γ⊬m"
        adm = "ADMISSIBLE" if r["ADMISSIBLE_TRANSITION"] else "INADMISSIBLE"
        print(f"  {mark:15s} · {auth:5s} · {adm:12s} · {r['label']}")
        if r["first_witness"]:
            w = r["first_witness"]
            print(f"       witness h1={w['h1']} h2={w['h2']}: {w['P_before']}  →  {w['P_after']}")
    print("─" * 70)
    print(f"  NEGATIVE CONTROL (refuted witness, m=+3) : "
          f"{'COMPATIBLE ⇒ Q_break=FALSE ✅ audit confirmed' if q_break_on_refuted is False else 'BREAKS'}")
    print(f"  POSITIVE CONTROL (swap 1,2)              : "
          f"{'BREAKS ⇒ checker CAN detect ✅' if not pos['QUOTIENT_COMPATIBLE'] else 'FAILED to detect'}")
    print(f"  CHECKER_SOUND (clears refuted ∧ catches real) = {checker_sound}")
    print("─" * 70)
    print("  SEAM: πm=m̄π (compatibility)  ⟂  Γ⊢m (authorization)  — independent axes")
    print("  compatible ≠ authorized · a no-op can be compatible · a break can be 'authorized'")
    print(f"  receipt_hash = {receipt['receipt_hash'][:16]}…  · ΔA=0 · model_calls=0 · NO_COMMIT")

    out = Path(__file__).resolve().parent / "QUOTIENT_EQUIVARIANCE_V0_RECEIPT.json"
    out.write_text(json.dumps(receipt, indent=2, ensure_ascii=False))
    print(f"  → {out.name}")


if __name__ == "__main__":
    main()
