#!/usr/bin/env python3
"""
Oracle Town Real-Time Cycle Observer
Extracts governance insights from decision records and cycle outputs.
Appends facts to entity items.json files (never deletes, only supersedes).
"""

import json
import os
import re
import hashlib
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

ROOT_DIR = Path(__file__).parent.parent.parent  # oracle_town/
MEMORY_DIR = ROOT_DIR / "memory"
DAILY_DIR = MEMORY_DIR / "daily"
ENTITIES_DIR = MEMORY_DIR / "entities"
META_DIR = MEMORY_DIR / "meta"
CKPT_PATH = META_DIR / "checkpoints.json"

# Ensure directories exist
DAILY_DIR.mkdir(parents=True, exist_ok=True)
ENTITIES_DIR.mkdir(parents=True, exist_ok=True)
META_DIR.mkdir(parents=True, exist_ok=True)

def load_json(path: Path, default=None):
    """Load JSON file, return default if missing."""
    if not path.exists():
        return default if default is not None else {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return default if default is not None else {}

def save_json(path: Path, obj: Any) -> None:
    """Save JSON file with sorted keys for determinism."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, sort_keys=True)

def fact_id(entity_type: str, entity_slug: str, fact_text: str, ts_iso: str) -> str:
    """Generate deterministic fact ID from content."""
    payload = f"{entity_type}:{entity_slug}:{fact_text}:{ts_iso}"
    h = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]
    return f"{entity_slug}-{h}"

def items_path(entity_type: str, entity_slug: str) -> Path:
    """Return path to items.json for entity."""
    return ENTITIES_DIR / entity_type / entity_slug / "items.json"

def summary_path(entity_type: str, entity_slug: str) -> Path:
    """Return path to summary.md for entity."""
    return ENTITIES_DIR / entity_type / entity_slug / "summary.md"

def ensure_entity(entity_type: str, entity_slug: str) -> None:
    """Create entity folder and initialize files if missing."""
    ip = items_path(entity_type, entity_slug)
    sp = summary_path(entity_type, entity_slug)
    ip.parent.mkdir(parents=True, exist_ok=True)

    if not ip.exists():
        save_json(ip, [])
    if not sp.exists():
        with open(sp, "w", encoding="utf-8") as f:
            f.write(f"# {entity_type}: {entity_slug}\n\n(autogenerated)\n")

def append_fact(
    entity_type: str,
    entity_slug: str,
    fact_text: str,
    category: str,
    source: str = "cycle_output",
    evidence: Optional[Dict] = None,
    confidence: float = 1.0
) -> bool:
    """
    Append fact to entity items.json.
    Returns True if added, False if duplicate.
    """
    ensure_entity(entity_type, entity_slug)
    ip = items_path(entity_type, entity_slug)
    items = load_json(ip, [])

    ts_iso = datetime.now().isoformat(timespec="seconds")
    fid = fact_id(entity_type, entity_slug, fact_text, ts_iso)

    # Check for duplicate (same ID)
    if any(x.get("id") == fid for x in items if isinstance(x, dict)):
        return False

    # Build fact object
    fact_obj = {
        "id": fid,
        "fact": fact_text,
        "timestamp": ts_iso,
        "status": "active",
        "source": source,
        "entity_type": entity_type,
        "entity_slug": entity_slug,
        "category": category,
        "confidence": confidence
    }

    if evidence:
        fact_obj["evidence"] = evidence

    items.append(fact_obj)
    save_json(ip, items)
    return True

def extract_decision_insights(decision_record: Dict) -> List[Dict]:
    """
    Extract governance insights from a decision record.
    Returns list of (entity_type, entity_slug, fact, category, evidence) tuples.
    """
    insights = []

    run_id = decision_record.get("run_id", "unknown")
    claim_id = decision_record.get("claim_id", "unknown")
    decision = decision_record.get("decision", "UNKNOWN")
    blocking_reasons = decision_record.get("blocking_reasons", [])

    # Insight 1: Decision outcome
    entity_type = "decisions"
    entity_slug = f"{run_id}-{claim_id}"
    fact = f"Decision: {decision} for {claim_id}"
    evidence = {"run_id": run_id, "claim_id": claim_id}

    insights.append({
        "entity_type": entity_type,
        "entity_slug": entity_slug,
        "fact": fact,
        "category": "pattern_success" if decision == "SHIP" else "pattern_failure",
        "source": "cycle_output",
        "evidence": evidence,
        "confidence": 1.0
    })

    # Insight 2: Blocking reasons (if any)
    if blocking_reasons and decision == "NO_SHIP":
        reason_codes = [br.get("reason_code") for br in blocking_reasons if isinstance(br, dict)]
        for rc in set(reason_codes):
            entity_slug = f"blocker-{rc.lower()}"
            fact = f"Blocking reason {rc} triggered"
            insights.append({
                "entity_type": "invariant_events",
                "entity_slug": entity_slug,
                "fact": fact,
                "category": "constraint_violation",
                "source": "cycle_output",
                "evidence": {"reason_code": rc, "claim_id": claim_id},
                "confidence": 1.0
            })

    return insights

def extract_emergence_signals(cycle_output: Dict) -> List[Dict]:
    """
    Detect emergence signals from cycle output.
    Emergence = measurable phenomena not explicitly programmed.
    """
    insights = []

    # Look for convergence signals
    if "proposal_pool" in cycle_output and isinstance(cycle_output["proposal_pool"], list):
        proposals = cycle_output["proposal_pool"]
        if len(proposals) > 0:
            # Convergence detected if proposals have high similarity
            # (stub: simplified heuristic)
            if len(proposals) <= 3:
                insights.append({
                    "entity_type": "emergence_signals",
                    "entity_slug": "convergence-detected",
                    "fact": f"Proposal convergence detected ({len(proposals)} unique proposals)",
                    "category": "convergence",
                    "source": "pattern_detection",
                    "evidence": {"proposal_count": len(proposals)},
                    "confidence": 0.8
                })

    # Look for lane performance signals
    if "lane_outputs" in cycle_output and isinstance(cycle_output["lane_outputs"], dict):
        lanes = cycle_output["lane_outputs"]
        for lane_name, lane_output in lanes.items():
            if isinstance(lane_output, dict):
                entity_slug = f"lane-{lane_name.lower().replace(' ', '_')}"
                fact = f"Lane '{lane_name}' provided analysis"
                insights.append({
                    "entity_type": "lane_performance",
                    "entity_slug": entity_slug,
                    "fact": fact,
                    "category": "performance_metric",
                    "source": "pattern_detection",
                    "evidence": {"lane": lane_name},
                    "confidence": 0.9
                })

    return insights

def process_cycle(cycle_num: int, cycle_output: Dict) -> Dict:
    """
    Process a single governance cycle.
    Extracts insights and appends to memory.
    Returns summary of what was added.
    """
    added = 0
    superseded = 0
    entities_touched = []

    # Extract decision insights
    if "decision_record" in cycle_output:
        decision_insights = extract_decision_insights(cycle_output["decision_record"])
        for ins in decision_insights:
            if append_fact(
                ins["entity_type"],
                ins["entity_slug"],
                ins["fact"],
                ins["category"],
                ins["source"],
                ins.get("evidence"),
                ins.get("confidence", 1.0)
            ):
                added += 1
                if ins["entity_type"] not in entities_touched:
                    entities_touched.append(ins["entity_type"])

    # Extract emergence signals
    emergence_insights = extract_emergence_signals(cycle_output)
    for ins in emergence_insights:
        if append_fact(
            ins["entity_type"],
            ins["entity_slug"],
            ins["fact"],
            ins["category"],
            ins["source"],
            ins.get("evidence"),
            ins.get("confidence", 1.0)
        ):
            added += 1
            if ins["entity_type"] not in entities_touched:
                entities_touched.append(ins["entity_type"])

    # Log daily note
    daily_log_path = DAILY_DIR / f"cycle-{cycle_num:03d}.json"
    daily_log = {
        "cycle_num": cycle_num,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "decision": cycle_output.get("decision_record", {}).get("decision", "UNKNOWN"),
        "facts_extracted": added,
        "entities_touched": entities_touched
    }
    save_json(daily_log_path, daily_log)

    return {
        "cycle_num": cycle_num,
        "facts_added": added,
        "facts_superseded": superseded,
        "entities_touched": entities_touched,
        "daily_log": str(daily_log_path)
    }

def update_checkpoints(last_cycle: int) -> None:
    """Update extraction checkpoint."""
    ckpt = load_json(CKPT_PATH, {})
    ckpt["last_cycle_processed"] = last_cycle
    ckpt["last_extraction_ts"] = datetime.now().isoformat(timespec="seconds")
    if "extraction_runs" not in ckpt:
        ckpt["extraction_runs"] = []
    ckpt["extraction_runs"].append({
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "last_cycle": last_cycle
    })
    save_json(CKPT_PATH, ckpt)

def process_test_runs():
    """Process test runs from memory/test_runs/ (for test harness)."""
    test_runs_dir = MEMORY_DIR / "test_runs"
    if not test_runs_dir.exists():
        print("No test_runs directory found.")
        return

    processed = 0
    for test_file in sorted(test_runs_dir.glob("week_*.json")):
        cycle_data = load_json(test_file, {})
        if not cycle_data:
            continue

        week_num = cycle_data.get("week_num", 0)
        run_id = cycle_data.get("run_id", "unknown")

        print(f"Processing {test_file.name} ({run_id})...")

        # Extract decisions
        for decision in cycle_data.get("decisions", []):
            claim_id = decision.get("claim_id", "unknown")
            dec = decision.get("decision", "UNKNOWN")
            blocking = decision.get("blocking_reasons", [])

            # Log decision
            entity_slug = f"{run_id}-{claim_id}"
            fact = f"Decision: {dec} for {claim_id}"
            append_fact(
                "decisions",
                entity_slug,
                fact,
                "pattern_success" if dec == "SHIP" else "pattern_failure",
                "test_cycle_output",
                {"run_id": run_id, "claim_id": claim_id},
                1.0
            )

            # Log blocking reasons
            for reason in blocking:
                append_fact(
                    "invariant_events",
                    f"blocker-{reason.lower()}",
                    f"Blocking reason {reason} triggered",
                    "constraint_violation",
                    "test_cycle_output",
                    {"reason": reason, "claim_id": claim_id},
                    1.0
                )

        processed += 1
        print(f"  ✓ Processed week {week_num}")

    print(f"\n✅ Processed {processed} test cycles.")

def main():
    """
    Main entry point.
    Usage: python3 cycle_observer.py <cycle_num> <cycle_output_json>
    Or: python3 cycle_observer.py --scan-runs
    Or: python3 cycle_observer.py --test-runs
    """
    import sys

    if len(sys.argv) < 2:
        print("Usage: cycle_observer.py <cycle_num> <cycle_output_json>")
        print("  Or: cycle_observer.py --scan-runs (production runs)")
        print("  Or: cycle_observer.py --test-runs (test harness runs)")
        sys.exit(1)

    if sys.argv[1] == "--test-runs":
        process_test_runs()
        return

    if sys.argv[1] == "--scan-runs":
        # Scan oracle_town/runs/ for existing run data
        runs_dir = ROOT_DIR / "runs"
        if runs_dir.exists():
            for run_folder in sorted(runs_dir.iterdir()):
                if not run_folder.is_dir():
                    continue
                decision_record = run_folder / "decision_record.json"
                if decision_record.exists():
                    print(f"Processing {run_folder.name}...")
                    decision = load_json(decision_record, {})
                    # Extract from existing data (simplified)
                    insights = extract_decision_insights(decision)
                    for ins in insights:
                        append_fact(
                            ins["entity_type"],
                            ins["entity_slug"],
                            ins["fact"],
                            ins["category"],
                            "cycle_output",
                            ins.get("evidence"),
                            1.0
                        )
        print("Scan complete.")
        return

    # Standard flow: process single cycle
    cycle_num = int(sys.argv[1])

    if len(sys.argv) >= 3:
        cycle_output_file = sys.argv[2]
        cycle_output = load_json(Path(cycle_output_file), {})
    else:
        # Try to find decision file
        decision_file = ROOT_DIR / "decisions" / f"decision_RUN_MODE_A_{cycle_num:03d}.json"
        if decision_file.exists():
            cycle_output = {"decision_record": load_json(decision_file, {})}
        else:
            print(f"No cycle output found for cycle {cycle_num}")
            sys.exit(1)

    result = process_cycle(cycle_num, cycle_output)
    update_checkpoints(cycle_num)

    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
