#!/usr/bin/env python3
"""
Oracle Town Weekly Synthesizer
Regenerates summaries, supersedes outdated facts, updates heuristics.
Runs weekly (e.g., Sunday 03:10).
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Any

ROOT_DIR = Path(__file__).parent.parent.parent  # oracle_town/
MEMORY_DIR = ROOT_DIR / "memory"
ENTITIES_DIR = MEMORY_DIR / "entities"
META_DIR = MEMORY_DIR / "meta"
TACIT_DIR = MEMORY_DIR / "tacit"
CKPT_PATH = META_DIR / "checkpoints.json"

def load_json(path: Path, default=None):
    """Load JSON file."""
    if not path.exists():
        return default if default is not None else {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return default if default is not None else {}

def save_json(path: Path, obj: Any) -> None:
    """Save JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, sort_keys=True)

def regenerate_summary(entity_type: str, entity_slug: str, items: List[Dict]) -> str:
    """
    Regenerate summary.md from active facts.
    Shows last 12 active facts, most recent first.
    """
    active_facts = [
        x for x in items
        if isinstance(x, dict) and x.get("status") == "active" and x.get("fact")
    ]

    # Sort by timestamp, newest first
    active_facts.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

    lines = [
        f"# {entity_type}: {entity_slug}",
        "",
        "## Current snapshot (last 12 active facts)",
        ""
    ]

    if not active_facts:
        lines.append("(no active facts)")
        lines.append("")
    else:
        for fact in active_facts[:12]:
            ts = fact.get("timestamp", "")[:10]  # Date only
            cat = fact.get("category", "unknown")
            conf = fact.get("confidence", 1.0)
            lines.append(f"- **{fact['fact']}**")
            lines.append(f"  - *category: {cat}*")
            lines.append(f"  - *timestamp: {ts}, confidence: {conf:.1%}*")
            lines.append("")

    lines.extend([
        "## Metadata",
        "",
        f"- Total active facts: {len(active_facts)}",
        f"- Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "(autogenerated by weekly_synthesizer.py)",
        ""
    ])

    return "\n".join(lines)

def detect_contradictions(items: List[Dict]) -> List[tuple]:
    """
    Detect facts that contradict each other.
    Simple heuristic: if newer fact mentions "no longer", "left", "former",
    mark older facts about "manager", "works together" as contradicted.

    Returns list of (fact_id_to_supersede, new_fact_id) tuples.
    """
    contradictions = []

    # Find "termination" facts
    termination_keywords = ["no longer", "left ", "former ", "ended ", "stopped "]
    new_facts = [
        x for x in items
        if isinstance(x, dict) and x.get("status") == "active"
    ]
    new_facts.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

    for new_fact in new_facts:
        fact_text = (new_fact.get("fact") or "").lower()
        if any(kw in fact_text for kw in termination_keywords):
            # Look for older facts that might be contradicted
            old_keywords = ["manager", "works together", "reports to", "colleague", "team member"]
            for old_fact in new_facts:
                if old_fact["id"] == new_fact["id"]:
                    continue
                if old_fact.get("status") != "active":
                    continue
                old_text = (old_fact.get("fact") or "").lower()
                if any(kw in old_text for kw in old_keywords):
                    if old_fact.get("timestamp", "") < new_fact.get("timestamp", ""):
                        contradictions.append((old_fact["id"], new_fact["id"]))

    return contradictions

def supersede_fact(items: List[Dict], old_id: str, new_id: str) -> bool:
    """Mark old_id as superseded by new_id. Returns True if modified."""
    for item in items:
        if not isinstance(item, dict):
            continue
        if item.get("id") == old_id and item.get("status") == "active":
            item["status"] = "superseded"
            item["supersededBy"] = new_id
            return True
    return False

def update_heuristics(entities_data: Dict[str, Dict]) -> None:
    """
    Update tacit/heuristics.md based on entity statistics.
    """
    heuristics_path = TACIT_DIR / "heuristics.md"
    heuristics = ""

    if heuristics_path.exists():
        with open(heuristics_path, "r", encoding="utf-8") as f:
            heuristics = f.read()

    # Add section footer with last update
    updated_heuristics = heuristics.rstrip() + "\n\n---\n\n"
    updated_heuristics += f"*Last updated: {datetime.now().isoformat(timespec='seconds')}*\n"

    # Add synthesis summary
    synthesis_notes = []
    for entity_type, slugs in entities_data.items():
        total = sum(len(items) for items in slugs.values())
        active = sum(
            len([x for x in items if isinstance(x, dict) and x.get("status") == "active"])
            for items in slugs.values()
        )
        synthesis_notes.append(f"- {entity_type}: {total} total, {active} active")

    if synthesis_notes:
        updated_heuristics += "*Synthesis run stats:*\n"
        updated_heuristics += "\n".join(synthesis_notes) + "\n"

    with open(heuristics_path, "w", encoding="utf-8") as f:
        f.write(updated_heuristics)

def run_weekly_synthesis() -> Dict:
    """
    Main synthesis logic.
    Returns summary of work done.
    """
    summary = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "entities_processed": 0,
        "summaries_regenerated": 0,
        "facts_superseded": 0,
        "contradictions_found": 0
    }

    entities_data = {}

    # Iterate over all entity types
    for entity_type_dir in sorted(ENTITIES_DIR.iterdir()):
        if not entity_type_dir.is_dir():
            continue

        entity_type = entity_type_dir.name
        entities_data[entity_type] = {}

        for entity_slug_dir in sorted(entity_type_dir.iterdir()):
            if not entity_slug_dir.is_dir():
                continue

            entity_slug = entity_slug_dir.name
            items_file = entity_slug_dir / "items.json"
            summary_file = entity_slug_dir / "summary.md"

            if not items_file.exists():
                continue

            items = load_json(items_file, [])
            entities_data[entity_type][entity_slug] = items

            # Detect contradictions
            contradictions = detect_contradictions(items)
            for old_id, new_id in contradictions:
                if supersede_fact(items, old_id, new_id):
                    summary["facts_superseded"] += 1
                    summary["contradictions_found"] += 1

            # Regenerate summary
            new_summary = regenerate_summary(entity_type, entity_slug, items)
            with open(summary_file, "w", encoding="utf-8") as f:
                f.write(new_summary)
            summary["summaries_regenerated"] += 1

            # Save updated items
            save_json(items_file, items)

            summary["entities_processed"] += 1

    # Update heuristics
    update_heuristics(entities_data)

    # Update checkpoint
    ckpt = load_json(CKPT_PATH, {})
    ckpt["last_synthesis_ts"] = datetime.now().isoformat(timespec="seconds")
    if "synthesis_runs" not in ckpt:
        ckpt["synthesis_runs"] = []
    ckpt["synthesis_runs"].append({
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "entities_processed": summary["entities_processed"],
        "summaries_regenerated": summary["summaries_regenerated"],
        "facts_superseded": summary["facts_superseded"]
    })

    save_json(CKPT_PATH, ckpt)

    return summary

def main():
    """Run weekly synthesis."""
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "--dry-run":
        print("[DRY RUN] Would run weekly synthesis")
        return

    result = run_weekly_synthesis()
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
