#!/usr/bin/env python3
"""
ORACLE TOWN — Level 2 Authority: Claim Schema

A claim is a proposal to mutate shared state.
Claims are generated by Labor (OBS, INS, BRF, PUB, MEM, EVO).
Claims are ratified by TRI + Mayor + Ledger.

No claim is allowed to ratify itself.
Ratification requires: TRI verdict + Mayor signature + Ledger commit.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from enum import Enum
import json
from datetime import datetime
from pathlib import Path


class ClaimType(str, Enum):
    """What kind of change is being proposed."""
    CODE_CHANGE = "code_change"
    SKILL_UPDATE = "skill_update"
    POLICY_PATCH = "policy_patch"
    MANIFEST_UPDATE = "manifest_update"
    KEY_REGISTRY_UPDATE = "key_registry_update"


class DiffOperation(str, Enum):
    """What operation is proposed for each file."""
    CREATE = "create"
    MODIFY = "modify"
    DELETE = "delete"


class EvidenceType(str, Enum):
    """What kind of evidence supports this claim."""
    TEST_RESULT = "test_result"
    DETERMINISM_CHECK = "determinism_check"
    LINT_RESULT = "lint_result"
    TYPE_CHECK = "type_check"
    SECURITY_SCAN = "security_scan"
    POLICY_CONFORMANCE = "policy_conformance"
    ARTIFACT_HASH = "artifact_hash"


@dataclass
class Diff:
    """A single proposed file change."""
    path: str
    operation: DiffOperation
    hash_before: Optional[str] = None  # sha256: of file before change
    hash_after: Optional[str] = None   # sha256: of file after change
    diff_url: Optional[str] = None     # path to .patch file

    def to_dict(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "operation": self.operation.value,
            "hash_before": self.hash_before,
            "hash_after": self.hash_after,
            "diff_url": self.diff_url,
        }


@dataclass
class EvidencePointer:
    """A reference to evidence that supports the claim."""
    type: EvidenceType
    path: str  # path to artifact in artifacts/ or oracle_town/
    hash: str  # sha256: of the evidence file
    description: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": self.type.value,
            "path": self.path,
            "hash": self.hash,
            "description": self.description,
        }


@dataclass
class AcceptanceCriteria:
    """
    Machine-checkable acceptance criteria for a claim.

    Required to make claim validity deterministic (not ambiguous).
    If missing or incomplete, TRI gate rejects claim automatically (K1 fail-closed).
    """

    success_conditions: List[str]  # e.g., ["test_pass", "coverage >= 85%", "no_lint_errors"]
    disallowed_side_effects: List[str] = None  # e.g., ["credential_exposure", "file_delete"]
    falsifiers: List[str] = None  # e.g., ["if_security_scan_fails", "if_policy_drift"]
    rollback_plan: Dict[str, Any] = None  # how to undo if needed

    def __post_init__(self):
        if self.disallowed_side_effects is None:
            self.disallowed_side_effects = []
        if self.falsifiers is None:
            self.falsifiers = []
        if self.rollback_plan is None:
            self.rollback_plan = {}

    def is_complete(self) -> bool:
        """Check if criteria is properly defined (not ambiguous)."""
        return (
            len(self.success_conditions) > 0 and
            all(isinstance(c, str) and len(c) > 0 for c in self.success_conditions) and
            isinstance(self.disallowed_side_effects, list) and
            isinstance(self.falsifiers, list)
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success_conditions": self.success_conditions,
            "disallowed_side_effects": self.disallowed_side_effects,
            "falsifiers": self.falsifiers,
            "rollback_plan": self.rollback_plan,
        }


@dataclass
class CompiledClaim:
    """
    A compiled claim for K-gate evaluation.
    Minimal schema for governance regression testing.

    This class represents a simplified claim object used by the K-gate
    validation layer for deterministic assessment of attestor authority,
    evidence completeness, and policy pinning.
    """
    claim_id: str
    statement: str
    evidence: List[str]
    attestor_id: str
    policy_version: str
    timestamp: str


# Compatibility alias for legacy tests and imports
TownInput = CompiledClaim


@dataclass
class Obligation:
    """
    Placeholder for obligation schema compatibility.
    Legacy code references this; governance logic uses other classes.
    """
    obligation_id: str
    description: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "obligation_id": self.obligation_id,
            "description": self.description,
        }


@dataclass
class Claim:
    """
    A claim is a proposal to mutate shared state.

    Invariants:
    - A claim is immutable once created (for audit trail)
    - A claim includes all evidence it relies on
    - A claim declares the policy pack hash it was generated under
    - A claim cannot ratify itself (requires TRI + Mayor)
    - A claim MUST include machine-checkable acceptance criteria (K1 fail-closed on ambiguity)
    """

    id: str  # claim_YYYYMMDD_<uuid>
    timestamp: str  # ISO 8601
    target: str  # what module/file is being changed
    claim_type: ClaimType

    proposed_diffs: List[Diff]
    evidence_pointers: List[EvidencePointer]
    expected_outcomes: List[str]  # e.g., ["all_tests_pass", "determinism_verified"]

    # NEW: Mandatory acceptance criteria (makes claim falsifiable)
    acceptance_criteria: AcceptanceCriteria  # REQUIRED; TRI rejects if missing/incomplete

    policy_pack_hash: str  # sha256: of pinned policy for this run
    generated_by: str  # attestor_id or labor component name
    intent: str  # human-readable description of why

    # Optional: for traceability
    parent_claim_id: Optional[str] = None  # if this claim amends another
    supersedes_claim_id: Optional[str] = None  # if this replaces another

    def to_dict(self) -> Dict[str, Any]:
        """Convert to JSON-serializable dict."""
        return {
            "claim": {
                "id": self.id,
                "timestamp": self.timestamp,
                "target": self.target,
                "claim_type": self.claim_type.value,
                "proposed_diffs": [d.to_dict() for d in self.proposed_diffs],
                "evidence_pointers": [e.to_dict() for e in self.evidence_pointers],
                "expected_outcomes": self.expected_outcomes,
                "acceptance_criteria": self.acceptance_criteria.to_dict(),
                "policy_pack_hash": self.policy_pack_hash,
                "generated_by": self.generated_by,
                "intent": self.intent,
                "parent_claim_id": self.parent_claim_id,
                "supersedes_claim_id": self.supersedes_claim_id,
            }
        }

    def to_json(self, indent: int = 2) -> str:
        """Serialize to JSON string (canonical format)."""
        data = self.to_dict()
        return json.dumps(data, sort_keys=True, indent=indent, ensure_ascii=True) + "\n"

    def save(self, path: Path) -> None:
        """Write claim to file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            f.write(self.to_json())

    @staticmethod
    def load(path: Path) -> Claim:
        """Load claim from file."""
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        claim_data = data["claim"]

        diffs = [
            Diff(
                path=d["path"],
                operation=DiffOperation(d["operation"]),
                hash_before=d.get("hash_before"),
                hash_after=d.get("hash_after"),
                diff_url=d.get("diff_url"),
            )
            for d in claim_data.get("proposed_diffs", [])
        ]

        evidence = [
            EvidencePointer(
                type=EvidenceType(e["type"]),
                path=e["path"],
                hash=e["hash"],
                description=e.get("description"),
            )
            for e in claim_data.get("evidence_pointers", [])
        ]

        # Load acceptance criteria (REQUIRED)
        ac_data = claim_data.get("acceptance_criteria")
        if not ac_data:
            raise ValueError(f"Claim {claim_data['id']} missing acceptance_criteria (K1 fail-closed)")

        acceptance_criteria = AcceptanceCriteria(
            success_conditions=ac_data.get("success_conditions", []),
            disallowed_side_effects=ac_data.get("disallowed_side_effects", []),
            falsifiers=ac_data.get("falsifiers", []),
            rollback_plan=ac_data.get("rollback_plan", {}),
        )

        return Claim(
            id=claim_data["id"],
            timestamp=claim_data["timestamp"],
            target=claim_data["target"],
            claim_type=ClaimType(claim_data["claim_type"]),
            proposed_diffs=diffs,
            evidence_pointers=evidence,
            expected_outcomes=claim_data.get("expected_outcomes", []),
            acceptance_criteria=acceptance_criteria,
            policy_pack_hash=claim_data["policy_pack_hash"],
            generated_by=claim_data["generated_by"],
            intent=claim_data["intent"],
            parent_claim_id=claim_data.get("parent_claim_id"),
            supersedes_claim_id=claim_data.get("supersedes_claim_id"),
        )
